# Generated by Django 5.1 on 2024-09-06 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
